-- Создаем таблицу заказов
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  username TEXT,
  full_name TEXT,
  items JSONB NOT NULL,
  total INTEGER NOT NULL,
  profile JSONB,
  items_summary TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Разрешаем чтение и запись для всех (для мини-приложения)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Политика для вставки заказов
CREATE POLICY "Allow inserts" ON orders
  FOR INSERT WITH CHECK (true);
